name: Pipeline

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo "Hola mundo"
      - name: fecha
        run: date
