name: Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with: 
          fetch-depth: 0
      - uses: actions/setup-node@v4.2.0
        with:
          node-version: "14" 
      - name: Instalar Dependencias
        run: npm install --no-audit --no-fund --no-optional
      - name : Build Proyect
        run: npm build
          
